### ISSUE TITLE
Localization Support

### ISSUE THREAD

**Issue by TartaricAcid** [Harystolho/ModpackDownloader#2]
Could you add a localization support for the downloader?
And support more font in different countries?

**Comment by victorbrndls** [comment]
When you say "localization support" you mean, choose the download file?

**Comment by TartaricAcid** [comment]
Button Text & GUI's Description

**Comment by victorbrndls** [comment]
Other languages ?

**Comment by TartaricAcid** [comment]
Yes.

**Comment by victorbrndls** [comment]
Okay, If I added an option for you to choose what mods to download, what you like it ?

**Comment by TartaricAcid** [comment]
Yes, I think it's good!

**Comment by victorbrndls** [comment]
Take a look a the version, tell me what you think
