### ISSUE TITLE
New ui is too large for my screen!

### ISSUE THREAD

**Issue by yuanjie000** [Harystolho/ModpackDownloader#3]
![qq 20180226122039](https://user-images.githubusercontent.com/20902900/36653375-b2756790-1aef-11e8-9b81-4c016923b29d.png)
win10: 16299.248
screen: 1366x768

**Comment by TartaricAcid** [comment]
I think `848x480` is better

**Comment by victorbrndls** [comment]
Thank you for the feedback, I will try to make it so you can resize it
